version: '3'
services:
  db:
    image: postgres
    container_name: easy-pairing-db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    container_name: easy-pairing-api
    command: >
      bash -c "rm -f tmp/pids/server.pid
      && bundle install
      && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db